version: '3'
services:

    php:
        image: php:7-apache
        container_name: pa
        restart: always
        volumes:
            - ../site/:/var/www/html
        ports:
            - 80:80
        
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpw
            - MYSQL_DATABASE=yamroll
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=1234

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: lemp-phpmyadmin
        restart: always
        ports:
        - "8000:80"
