version: '3'
services:

    php:
        image: php:7-apache
        container_name: pa
        volumes:
            - ../site/:/var/www/html
        ports:
            - 80:80
        
    db:
        image: mariadb:latest
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=rootpw
            - MYSQL_DATABASE=yamroll
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=1234
